name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3  # Checkout the repository

      # Set up Ruby environment for Jekyll
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_<YOUR_APP_NAME> }}  # Make sure your secret is correctly set
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_deploy_on_missing_secrets: true  # Skips deployment if the secret is missing
          app_location: "/"
          output_location: "_site"
